#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l vmem=6gb
#PBS -l walltime=01:00:00

set -e
set -x

# networkName=$(jq -r .network config.json)
# realizations=$(jq -r .realizations config.json)
# alpha=$(jq -r .alpha config.json)
# ./main.py $networkName $realizations $alpha

chmod +x main.py
SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://filsilva/cxnetwork:0.2.0 ./main.py config.json

echo "done"



